# Generated by Django 5.1.4 on 2025-01-13 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHECKING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chck', models.CharField(choices=[('T', 'Tire'), ('B', 'Brakes'), ('L', 'Lights'), ('E', 'Engine Oil'), ('F', 'Feel')], default='T', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
