# Generated by Django 5.1.4 on 2025-01-14 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_service_car_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checking',
            name='chck',
            field=models.CharField(choices=[('T', 'Tire'), ('B', 'Brakes'), ('L', 'Lights'), ('E', 'Engine Oil'), ('F', 'Fuel')], default='T', max_length=1),
        ),
    ]
